
{{
  config(
    materialized='view'
  )
}}

WITH src_promos AS (
    SELECT
    *
    FROM {{ source('sql_server_dbo','promos') }}
)

SELECT
    MD5(PROMO_ID) AS PROMO_ID,
    PROMO_ID AS PROMO_NAME,
    DISCOUNT::NUMERIC(38,2) AS DISCOUNT_DOLLARS,
    CASE WHEN STATUS = 'active' THEN TRUE ELSE FALSE END::BOOLEAN  AS IS_ACTIVE_STATUS,
    _FIVETRAN_DELETED,
    CONVERT_TIMEZONE('UTC',_FIVETRAN_SYNCED) AS _FIVETRAN_SYNCED 
    FROM src_promos
    WHERE _FIVETRAN_DELETED IS NULL

UNION ALL

SELECT
    MD5('NO_PROMO') AS PROMO_ID,
    'NO_PROMO' AS PROMO_NAME,
    0 AS DISCOUNT_DOLLARS,
    FALSE AS STATUS,
    NULL AS _FIVETRAN_DELETED,
    NULL AS _FIVETRAN_SYNCED